language: node_js
dist: bionic
node_js:
  - 10
cache:
  yarn: true
  directories:
    - .git/lfs
env:
  - BUILD_HOST=travis-ci
git:
  lfs_skip_smudge: true
install:
  - git lfs pull
  - yarn
script:
  - npm run lint:before
  - npm run build
  - npm run lint:after
addons:
  ssh_known_hosts: szp15.com
before_install:
  - sudo apt-get -y install ditaa graphviz librsvg2-bin ttf-wqy-microhei
  - export TZ=Asia/Shanghai
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - chmod 600 /tmp/deploy_rsa
  - eval "$(ssh-agent -s)"
  - DISPLAY=":0.0" setsid ssh-add /tmp/deploy_rsa </dev/null
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/site/.vuepress/dist/ sun@szp15.com:/srv/http/blog
  on:
    branch: master
